# Generated by Django 4.1.2 on 2022-12-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LES1', '0004_alter_userdata_re_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('Tittle', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('User1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LES1.userdata')),
            ],
        ),
    ]
