# Generated by Django 4.1.2 on 2022-12-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LES1', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Date',
        ),
    ]
