# Generated by Django 4.1.2 on 2022-12-11 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LES1', '0006_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Day',
            field=models.DateField(default=datetime.date(2022, 12, 11)),
        ),
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='Tittle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
