# Generated by Django 4.1.2 on 2022-12-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LES1', '0009_alter_event_day_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.TextField(max_length=50),
        ),
    ]
