# Generated by Django 4.1.2 on 2022-12-16 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LES1", "0012_alter_event_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="anonymous", max_length=200)),
                ("topic", models.CharField(max_length=300)),
                ("Question", models.CharField(blank=True, max_length=1000)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="Day",
            field=models.DateField(default=datetime.date(2022, 12, 16)),
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="anonymous", max_length=200)),
                ("discuss", models.CharField(max_length=1000)),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LES1.forum",
                    ),
                ),
            ],
        ),
    ]
