# Generated by Django 4.1.2 on 2022-12-22 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LES1", "0015_alter_event_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discussion", old_name="forum", new_name="Question",
        ),
        migrations.AlterField(
            model_name="event",
            name="Day",
            field=models.DateField(default=datetime.date(2022, 12, 22)),
        ),
    ]
