# Generated by Django 4.1.2 on 2022-12-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LES1", "0016_rename_forum_discussion_question_alter_event_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discussion", old_name="Question", new_name="forum",
        ),
    ]
